name: Build Performance Foundation Site Zip

on: 
  schedule:
    - cron: '0 11 * * *'  # Everyday at 4am PST
      
  workflow_dispatch:
    inputs:
      container:
        default: "xmcloudperformancefoundation"
        description: "Container to upload the artifact."
        required: true
      storageAccount:
        default: "qepeformanceteamresults"
        description: "The storage account name used to upload artifact."
        required: true
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v4
        with:
          path: "~/.local/share/powershell/Modules"
          key: ${{ runner.os }}-Az-Storage
      - name: Install required PowerShell modules
        if: steps.cacher.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az.Storage -ErrorAction Stop
          Install-Module Az.Resources -ErrorAction Stop
          Install-Module AzTable -ErrorAction Stop
      - name: Checkout lhdatagenerator
        uses: actions/checkout@v4
        with:
          path: "lhdatagenerator"

      - name: Checkout Foundation Site
        uses: actions/checkout@v4
        
        with:
          repository: 'sitecorelabs/xmcloud-foundation-head'
          path: "src"

      - name: Build Performance Foundation Artifact
        shell: pwsh
        run: |
          ./lhdatagenerator/New-PerformanceSitePackage.ps1
        working-directory: ./
          
      
      - name: Create ZIp
        shell: pwsh
        run: |
          rm -rf artifacts.zip
          cd ./src
          zip -r artifacts.zip .
      
      - name: Push to Blob
        shell: pwsh
        env:
          BLOBSTORAGEKEY: ${{ secrets.BLOBSTORAGEKEY }}
          CONTAINERNAME: ${{ github.event.inputs.container }}
          STORAGEACCOUNTNAME: ${{ github.event.inputs.storageAccount }}
        run: |
          $storageAccountName = $env:STORAGEACCOUNTNAME
          $containerName = $env:CONTAINERNAME
          if (-not ($env:STORAGEACCOUNTNAME)) { $storageAccountName = "qepeformanceteamresults" }
          if (-not ($env:CONTAINERNAME)) { $containerName = "xmcloudperformancefoundation" }
          Write-Host "Storage Account Name: $storageAccountName"
          Write-Host "Blob Container Name: $containerName"
          $context = New-AzStorageContext -StorageAccountName $storageAccountName -StorageAccountKey $env:BLOBSTORAGEKEY
          $blob = @{
                    File             = "./src/artifacts.zip"
                    Container        = $containerName
                    Blob             = "artifacts.zip"
                    Context          = $context
                    StandardBlobTier = 'Hot'
          }
          Set-AzStorageBlobContent @blob -Force

      - name: Add Site to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "artifacts"
          path: src
